### PR TITLE
Fixed can paste value into read-only date field

### LINKED ISSUE #1386: User can still paste into read-only date field
**Describe the bug**
Users were able to copy and paste values into date fields on forms, even though those fields were set to read-only, which should not have been allowed.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

1. Open some form with read-only date field in it.
2. Copy some date value from text editor into clipboard, for example 2024-07-07.
3. Click the read-only date field.
4. Press Ctrl/Cmd+V.
5. Copied value pasted into the read-only date field.

**Expected behavior**
Copied value should not be pasted into the field.

**Browser and OS (please complete the following information):**

-   OS: Windows 11
-   Browser Edge, Chrome

### PR DESCRIPTION
**Pull request by gushil**
Closes #1386 

#### I have verified this PR works with

-   [x] Online form submission
-   [ ] Offline form submission
-   [ ] Saving offline drafts
-   [ ] Loading offline drafts
-   [x] Editing submissions
-   [x] Form preview
-   [ ] None of the above

#### What else has been done to verify that this works as intended?
Manual test.

#### Why is this the best possible solution? Were any other approaches considered?
Simple yet works.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
None.

#### Do we need any specific form for testing your changes? If so, please attach one.
No, just usual form with read-only date field in it.

### CODE REVIEW

File: packages/enketo-core/src/widget/date/datepicker-extended.js [hunk 1]
```diff
@@ -87,7 +87,12 @@ class DatepickerExtended extends Widget {
     _setChangeHandler($fakeDateI) {
         const { settings } = this;
 
-        $fakeDateI.on('change paste', (e) => {
+        let changeEvent = 'change';
+        if (!$fakeDateI.closest('label').hasClass('readonly')) {
+            changeEvent += ' paste';
+        }
+
+        $fakeDateI.on(changeEvent, (e) => {
```
Comment (lognaturel) [inline packages/enketo-core/src/widget/date/datepicker-extended.js:95]: Thanks for noticing this and taking on a fix! This works but feels a bit hard to understand to me. 

No `change` event should ever be fired on a readonly date, right? Could we instead not register the handler at all in that case? Something like 

```
if (!$fakeDateI.closest('label').hasClass('readonly')) {
  $fakeDateI.on('change paste', (e) => {
    ...
}
```

Comment (gushil) [reply packages/enketo-core/src/widget/date/datepicker-extended.js]: Got it. Adressed in the next commit.

Thanks.

**Review by lognaturel — APPROVED** [review]
Thank you!
