### PR TITLE
Fixed translation cache of element with i18nNumber

### LINKED ISSUE #1337: Problem of multiselect widgets in a repeating group displaying the same selected options
**Describe the bug**
The problem occurred when editing the form.

If the page contains multiple selectpickers with similar i18n keys (for example, in a repeating group), it will show the wrong selected text (even though the select options themselves are correct).

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

1. Create a form with multilselect in a repeating group.
2. Add some (2 or more) multiselect in form enketo page. Select different options and keep some multiselect have same number of options selected (for example first multiselect has 3 options selected, second multiselect has 2 options selected.
3. Close the form page to save the input.
4. Edit the same form.
5. We will see that the second multiselect will display **3 selected** instead of **2 selected**.

**Expected behavior**
The third multiselect should display **2 selected**

**Screenshots**
This multiselect xform instances
```
<group_nm7ec42  enk:ordinal="1" >
	<multiselect2>a b c</multiselect2>
</group_nm7ec42>
<group_nm7ec42  enk:ordinal="2" >
	<multiselect2>a b</multiselect2>
</group_nm7ec42>
```
will give us
wrong-select
instead of (the right one)
correct-select

**Browser and OS (please complete the following information):**

-   OS: Windows 11, MacOS
-   Browser: Chrome

**Additional context**
None.

### PR DESCRIPTION
**Pull request by gushil**
Closes #1337 

#### I have verified this PR works with

-   [ ] Online form submission
-   [ ] Offline form submission
-   [ ] Saving offline drafts
-   [ ] Loading offline drafts
-   [x] Editing submissions
-   [ ] Form preview
-   [ ] None of the above

#### What else has been done to verify that this works as intended?
Just found the problem in editing submission. I think that is sufficent in this case.

#### Why is this the best possible solution? Were any other approaches considered?
The usage of combination of i18n and i18nNumber as key is the fast way to cache the result.

Yes, other solution could be removing the usage of i18n (and i18nNumber) in selectpicker widget but that will render the cache useless in this case.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
None.

#### Do we need any specific form for testing your changes? If so, please attach one.
No, just usual multiselect in a repeating group.

### CODE REVIEW

File: packages/enketo-express/public/js/src/module/translator.js [hunk 1]
```diff
@@ -87,34 +87,44 @@ const localize = (container, lng) => {
...
         .then(() => {
             list.forEach((el) => {
-                const key = el.dataset.i18n;
+                let key = el.dataset.i18n;
+                // translation key for element with i18nNumber is i18n-i18nNumber
+                if (el.dataset.i18nNumber) {
+                    key = `${key}-${el.dataset.i18nNumber}`;
+                }
                 if (key) {
+                    let options = {};
```
Comment (lognaturel) [inline packages/enketo-express/public/js/src/module/translator.js:96]: Why did the option setting move out of the `!cache[key]` block? They only need to be set if there's going to be a new cache entry, right?

Comment (gushil) [reply packages/enketo-express/public/js/src/module/translator.js]: Yes, you are right.

Fixed.

Thanks for the suggestion!

**Review by lognaturel — APPROVED** [review]
I have quickly verified that this fixes the issue. It feels low risk.
